apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: canary
 annotations:
 nginx.ingress.kubernetes.io/canary: \"true\"
 nginx.ingress.kubernetes.io/canary-weight: \"30\"
spec:
 ingressClassName: nginx
 rules:
 - host: example.com
 http:
 paths:
 - pathType: Prefix
 path: /
 backend:
 service:
 name: canaryService
 port:
 number: 80